### ISSUE TITLE
What's the status and roadmap of this implementation?

### ISSUE THREAD

**Issue by raulk** [Agorise/c-libp2p#5]
Hello from the libp2p group at Protocol Labs! 👋

Thanks for your incredible work on getting this C implementation of libp2p started, @jmjatlanta @marcialvieira @raduiliescu83!

I was curious as to what the status was. Do you know of any applications using it? Any plans to continue making progress? Have you tested interoperability with other implementations?

There's another group starting a C++ implementation, and I think it would be worthwhile to align.

Cheers!

**Comment by jmjatlanta** [comment]
Thank you for your message. Unfortunately, this is not actively in development. I would love to see it move forward. A C++ implementation would also be great. I have heard of other projects considering using this as their p2p layer, but only in concept discussions.

**Comment by raulk** [comment]
Thanks for the answer! The C++ implementation is taking place here: https://github.com/soramitsu/kagome/tree/master/core/libp2p

**Comment by LLE8** [comment]
@raulk - 404
https://github.com/soramitsu/libp2p
